---
title: Weights and Measures
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  paintings:
    title: paintings
    output: false
  photographs:
    title: photographs
    output: true
email: bradleymccallum@me.com
description: |
  Weights and Measures is a socially engaged public art project, conceived by Bradley McCallum, that examines international justice through portraits.
baseurl: ''
url: http://example.com
markdown: kramdown
sass:
  sass_dir: css
